language: node_js
node_js:
  - "0.10"
services: mongodb

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


install:
  - "git clone https://github.com/meteor/meteor.git ~/meteor"
  - "export PATH=~/meteor/:$PATH"

  - "npm install -g meteorite"
  - "mrt update"
  - "sudo apt-get install libxss1 libappindicator1 libindicator7"
  - "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  - "sudo dpkg -i google-chrome*.deb "

before_script:
  - "meteor &"
  - sleep 120

script:
  - "./help.sh"
 
 
