language: node_js
node_js:
  - "0.10"
services: mongodb

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


install:
  - "git clone https://github.com/meteor/meteor.git ~/meteor"
  - "export PATH=~/meteor/:$PATH"

  - "npm install -g meteorite"
  - "mrt update"

before_script:
  - "meteor &"
  - sleep 20

script:
  - "./run_nightwatch.sh -t tests/helloworld.js"
 
 
